name: 04-using-actions
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    # 0 checkout the Code from the repository
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls

    #1. Install dependencies of ASP.NET Core MVC Application

    #2. Execute Automated Tests
    # If these are successful, we would like to, for example, build and publish the app
